set_property PACKAGE_PIN J17 [get_ports an[0]]
set_property PACKAGE_PIN J18 [get_ports an[1]]
set_property PACKAGE_PIN T9 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports prox[1]]
set_property IOSTANDARD LVCMOS33 [get_ports prox[0]]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports FAout]
set_property IOSTANDARD LVCMOS33 [get_ports firealarm]
set_property IOSTANDARD LVCMOS33 [get_ports BG]
set_property IOSTANDARD LVCMOS33 [get_ports BF1]
set_property IOSTANDARD LVCMOS33 [get_ports BF2]
set_property IOSTANDARD LVCMOS33 [get_ports BF3]
set_property IOSTANDARD LVCMOS33 [get_ports OLout]
set_property IOSTANDARD LVCMOS33 [get_ports overload]
set_property IOSTANDARD LVCMOS33 [get_ports reqG]
set_property IOSTANDARD LVCMOS33 [get_ports reqF1]
set_property IOSTANDARD LVCMOS33 [get_ports reqF2]
set_property IOSTANDARD LVCMOS33 [get_ports reqF3]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[5]}]


set_property IOSTANDARD LVCMOS33 [get_ports {an[4]}]
set_property PACKAGE_PIN J14 [get_ports {an[3]}]
set_property PACKAGE_PIN P14 [get_ports {an[4]}]
set_property PACKAGE_PIN T14 [get_ports {an[5]}]
set_property PACKAGE_PIN K2 [get_ports {an[6]}]
set_property PACKAGE_PIN U13 [get_ports {an[7]}]
set_property PACKAGE_PIN U18 [get_ports BF2]
set_property PACKAGE_PIN R13 [get_ports BF1]
set_property PACKAGE_PIN T8 [get_ports BG]
set_property PACKAGE_PIN T18 [get_ports BF3]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN V10 [get_ports firealarm]
set_property PACKAGE_PIN R17 [get_ports reqG]
set_property PACKAGE_PIN R15 [get_ports reqF1]
set_property PACKAGE_PIN M13 [get_ports reqF2]
set_property PACKAGE_PIN L16 [get_ports reqF3]
set_property PACKAGE_PIN J15 [get_ports reset]
set_property PACKAGE_PIN V11 [get_ports door_closed]
set_property PACKAGE_PIN V12 [get_ports door_open]
#set_property PACKAGE_PIN V15 [get_ports FAout]
#set_property PACKAGE_PIN U14 [get_ports OLout]
set_property PACKAGE_PIN R10 [get_ports {seg[1]}]
set_property PACKAGE_PIN T10 [get_ports {seg[0]}]
set_property PACKAGE_PIN K16 [get_ports {seg[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg[4]}]
set_property PACKAGE_PIN T11 [get_ports {seg[5]}]
set_property PACKAGE_PIN L18 [get_ports {seg[6]}]
set_property PACKAGE_PIN V17 [get_ports {prox[1]}]
set_property PACKAGE_PIN R18 [get_ports {prox[0]}]
set_property PACKAGE_PIN U11 [get_ports overload]

set_property -dict { PACKAGE_PIN M16   IOSTANDARD LVCMOS33 } [get_ports  door_open ]; #green led
set_property -dict { PACKAGE_PIN N15   IOSTANDARD LVCMOS33 } [get_ports  door_closed ];  #red led


set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports  FAout ]; #red led


set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports  OLout ]; #blue led 

